version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,DOCKER://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,DOCKER://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    depends_on:
      - kafka

  # jobmanager:
  #   image: flink:latest
  #   command: jobmanager
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - JOB_MANAGER_RPC_ADDRESS=jobmanager

  # taskmanager:
  #   image: flink:latest
  #   command: taskmanager
  #   depends_on:
  #     - jobmanager
  #   environment:
  #     - JOB_MANAGER_RPC_ADDRESS=jobmanager

  # flink-job:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile  # Ensure the Dockerfile is in the same directory as docker-compose.yml
  #   depends_on:
  #     - kafka
  #     - jobmanager
  #     - taskmanager

